android.useAndroidX=true
android.newDsl=false
android.builtInKotlin=false

org.gradle.jvmargs=-Xmx6g -Dfile.encoding=UTF-8
kotlin.native.jvmArgs=-Xmx6g
kotlin.native.cacheKind=none

org.gradle.parallel=true
org.gradle.caching=true
org.gradle.daemon=true

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
